

import "./cljs-runtime/shadow.module.server.prepend.js";
SHADOW_ENV.setLoaded("shadow.module.server.prepend.js");
import "./cljs-runtime/goog.debug.error.js";
SHADOW_ENV.setLoaded("goog.debug.error.js");
import "./cljs-runtime/goog.dom.nodetype.js";
SHADOW_ENV.setLoaded("goog.dom.nodetype.js");
import "./cljs-runtime/goog.asserts.asserts.js";
SHADOW_ENV.setLoaded("goog.asserts.asserts.js");
import "./cljs-runtime/goog.reflect.reflect.js";
SHADOW_ENV.setLoaded("goog.reflect.reflect.js");
import "./cljs-runtime/goog.math.long.js";
SHADOW_ENV.setLoaded("goog.math.long.js");
import "./cljs-runtime/goog.math.integer.js";
SHADOW_ENV.setLoaded("goog.math.integer.js");
import "./cljs-runtime/goog.dom.htmlelement.js";
SHADOW_ENV.setLoaded("goog.dom.htmlelement.js");
import "./cljs-runtime/goog.dom.tagname.js";
SHADOW_ENV.setLoaded("goog.dom.tagname.js");
import "./cljs-runtime/goog.dom.element.js";
SHADOW_ENV.setLoaded("goog.dom.element.js");
import "./cljs-runtime/goog.asserts.dom.js";
SHADOW_ENV.setLoaded("goog.asserts.dom.js");
import "./cljs-runtime/goog.dom.asserts.js";
SHADOW_ENV.setLoaded("goog.dom.asserts.js");
import "./cljs-runtime/goog.functions.functions.js";
SHADOW_ENV.setLoaded("goog.functions.functions.js");
import "./cljs-runtime/goog.string.typedstring.js";
SHADOW_ENV.setLoaded("goog.string.typedstring.js");
import "./cljs-runtime/goog.string.const.js";
SHADOW_ENV.setLoaded("goog.string.const.js");
import "./cljs-runtime/goog.html.trustedtypes.js";
SHADOW_ENV.setLoaded("goog.html.trustedtypes.js");
import "./cljs-runtime/goog.html.safescript.js";
SHADOW_ENV.setLoaded("goog.html.safescript.js");
import "./cljs-runtime/goog.fs.url.js";
SHADOW_ENV.setLoaded("goog.fs.url.js");
import "./cljs-runtime/goog.fs.blob.js";
SHADOW_ENV.setLoaded("goog.fs.blob.js");
import "./cljs-runtime/goog.html.trustedresourceurl.js";
SHADOW_ENV.setLoaded("goog.html.trustedresourceurl.js");
import "./cljs-runtime/goog.string.internal.js";
SHADOW_ENV.setLoaded("goog.string.internal.js");
import "./cljs-runtime/goog.html.safeurl.js";
SHADOW_ENV.setLoaded("goog.html.safeurl.js");
import "./cljs-runtime/goog.html.safestyle.js";
SHADOW_ENV.setLoaded("goog.html.safestyle.js");
import "./cljs-runtime/goog.object.object.js";
SHADOW_ENV.setLoaded("goog.object.object.js");
import "./cljs-runtime/goog.html.safestylesheet.js";
SHADOW_ENV.setLoaded("goog.html.safestylesheet.js");
import "./cljs-runtime/goog.flags.flags.js";
SHADOW_ENV.setLoaded("goog.flags.flags.js");
import "./cljs-runtime/goog.labs.useragent.useragent.js";
SHADOW_ENV.setLoaded("goog.labs.useragent.useragent.js");
import "./cljs-runtime/goog.labs.useragent.util.js";
SHADOW_ENV.setLoaded("goog.labs.useragent.util.js");
import "./cljs-runtime/goog.labs.useragent.highentropy.highentropyvalue.js";
SHADOW_ENV.setLoaded("goog.labs.useragent.highentropy.highentropyvalue.js");
import "./cljs-runtime/goog.labs.useragent.chromium_rebrands.js";
SHADOW_ENV.setLoaded("goog.labs.useragent.chromium_rebrands.js");
import "./cljs-runtime/goog.labs.useragent.highentropy.highentropydata.js";
SHADOW_ENV.setLoaded("goog.labs.useragent.highentropy.highentropydata.js");
import "./cljs-runtime/goog.labs.useragent.browser.js";
SHADOW_ENV.setLoaded("goog.labs.useragent.browser.js");
import "./cljs-runtime/goog.array.array.js";
SHADOW_ENV.setLoaded("goog.array.array.js");
import "./cljs-runtime/goog.dom.tags.js";
SHADOW_ENV.setLoaded("goog.dom.tags.js");
import "./cljs-runtime/goog.html.safehtml.js";
SHADOW_ENV.setLoaded("goog.html.safehtml.js");
import "./cljs-runtime/goog.html.uncheckedconversions.js";
SHADOW_ENV.setLoaded("goog.html.uncheckedconversions.js");
import "./cljs-runtime/goog.dom.safe.js";
SHADOW_ENV.setLoaded("goog.dom.safe.js");
import "./cljs-runtime/goog.string.string.js";
SHADOW_ENV.setLoaded("goog.string.string.js");
import "./cljs-runtime/goog.collections.maps.js";
SHADOW_ENV.setLoaded("goog.collections.maps.js");
import "./cljs-runtime/goog.structs.structs.js";
SHADOW_ENV.setLoaded("goog.structs.structs.js");
import "./cljs-runtime/goog.uri.utils.js";
SHADOW_ENV.setLoaded("goog.uri.utils.js");
import "./cljs-runtime/goog.uri.uri.js";
SHADOW_ENV.setLoaded("goog.uri.uri.js");
import "./cljs-runtime/goog.string.stringbuffer.js";
SHADOW_ENV.setLoaded("goog.string.stringbuffer.js");
import "./cljs-runtime/cljs.core.js";
SHADOW_ENV.setLoaded("cljs.core.js");
import "./cljs-runtime/shadow.js.js";
SHADOW_ENV.setLoaded("shadow.js.js");
import "./cljs-runtime/shadow.esm.esm_import$ws.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$ws.js");
import "./cljs-runtime/shadow.js.shim.module$ws$default.js";
SHADOW_ENV.setLoaded("shadow.js.shim.module$ws$default.js");
import "./cljs-runtime/clojure.string.js";
SHADOW_ENV.setLoaded("clojure.string.js");
import "./cljs-runtime/cljs.tools.reader.impl.utils.js";
SHADOW_ENV.setLoaded("cljs.tools.reader.impl.utils.js");
import "./cljs-runtime/cljs.tools.reader.reader_types.js";
SHADOW_ENV.setLoaded("cljs.tools.reader.reader_types.js");
import "./cljs-runtime/cljs.tools.reader.impl.inspect.js";
SHADOW_ENV.setLoaded("cljs.tools.reader.impl.inspect.js");
import "./cljs-runtime/cljs.tools.reader.impl.errors.js";
SHADOW_ENV.setLoaded("cljs.tools.reader.impl.errors.js");
import "./cljs-runtime/cljs.tools.reader.impl.commons.js";
SHADOW_ENV.setLoaded("cljs.tools.reader.impl.commons.js");
import "./cljs-runtime/cljs.tools.reader.js";
SHADOW_ENV.setLoaded("cljs.tools.reader.js");
import "./cljs-runtime/cljs.tools.reader.edn.js";
SHADOW_ENV.setLoaded("cljs.tools.reader.edn.js");
import "./cljs-runtime/cljs.reader.js";
SHADOW_ENV.setLoaded("cljs.reader.js");
import "./cljs-runtime/shadow.remote.runtime.api.js";
SHADOW_ENV.setLoaded("shadow.remote.runtime.api.js");
import "./cljs-runtime/shadow.remote.runtime.shared.js";
SHADOW_ENV.setLoaded("shadow.remote.runtime.shared.js");
import "./cljs-runtime/shadow.esm.js";
SHADOW_ENV.setLoaded("shadow.esm.js");
import "./cljs-runtime/clojure.set.js";
SHADOW_ENV.setLoaded("clojure.set.js");
import "./cljs-runtime/com.cognitect.transit.util.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.util.js");
import "./cljs-runtime/com.cognitect.transit.delimiters.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.delimiters.js");
import "./cljs-runtime/com.cognitect.transit.caching.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.caching.js");
import "./cljs-runtime/com.cognitect.transit.eq.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.eq.js");
import "./cljs-runtime/com.cognitect.transit.types.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.types.js");
import "./cljs-runtime/com.cognitect.transit.impl.decoder.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.impl.decoder.js");
import "./cljs-runtime/com.cognitect.transit.impl.reader.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.impl.reader.js");
import "./cljs-runtime/com.cognitect.transit.handlers.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.handlers.js");
import "./cljs-runtime/com.cognitect.transit.impl.writer.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.impl.writer.js");
import "./cljs-runtime/com.cognitect.transit.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.js");
import "./cljs-runtime/cognitect.transit.js";
SHADOW_ENV.setLoaded("cognitect.transit.js");
import "./cljs-runtime/shadow.cljs.devtools.client.env.js";
SHADOW_ENV.setLoaded("shadow.cljs.devtools.client.env.js");
import "./cljs-runtime/clojure.core.protocols.js";
SHADOW_ENV.setLoaded("clojure.core.protocols.js");
import "./cljs-runtime/shadow.remote.runtime.cljs.js_builtins.js";
SHADOW_ENV.setLoaded("shadow.remote.runtime.cljs.js_builtins.js");
import "./cljs-runtime/clojure.datafy.js";
SHADOW_ENV.setLoaded("clojure.datafy.js");
import "./cljs-runtime/cljs.pprint.js";
SHADOW_ENV.setLoaded("cljs.pprint.js");
import "./cljs-runtime/clojure.walk.js";
SHADOW_ENV.setLoaded("clojure.walk.js");
import "./cljs-runtime/cljs.spec.gen.alpha.js";
SHADOW_ENV.setLoaded("cljs.spec.gen.alpha.js");
import "./cljs-runtime/cljs.spec.alpha.js";
SHADOW_ENV.setLoaded("cljs.spec.alpha.js");
import "./cljs-runtime/shadow.remote.runtime.writer.js";
SHADOW_ENV.setLoaded("shadow.remote.runtime.writer.js");
import "./cljs-runtime/goog.string.stringformat.js";
SHADOW_ENV.setLoaded("goog.string.stringformat.js");
import "./cljs-runtime/cljs.repl.js";
SHADOW_ENV.setLoaded("cljs.repl.js");
import "./cljs-runtime/shadow.remote.runtime.obj_support.js";
SHADOW_ENV.setLoaded("shadow.remote.runtime.obj_support.js");
import "./cljs-runtime/shadow.remote.runtime.tap_support.js";
SHADOW_ENV.setLoaded("shadow.remote.runtime.tap_support.js");
import "./cljs-runtime/shadow.remote.runtime.eval_support.js";
SHADOW_ENV.setLoaded("shadow.remote.runtime.eval_support.js");
import "./cljs-runtime/shadow.cljs.devtools.client.shared.js";
SHADOW_ENV.setLoaded("shadow.cljs.devtools.client.shared.js");
import "./cljs-runtime/shadow.cljs.devtools.client.node_esm.js";
SHADOW_ENV.setLoaded("shadow.cljs.devtools.client.node_esm.js");
import "./cljs-runtime/knoxx.backend.contracts.actor_scope.js";
SHADOW_ENV.setLoaded("knoxx.backend.contracts.actor_scope.js");
import "./cljs-runtime/malli.impl.util.js";
SHADOW_ENV.setLoaded("malli.impl.util.js");
import "./cljs-runtime/malli.impl.regex.js";
SHADOW_ENV.setLoaded("malli.impl.regex.js");
import "./cljs-runtime/malli.registry.js";
SHADOW_ENV.setLoaded("malli.registry.js");
import "./cljs-runtime/borkdude.dynaload.js";
SHADOW_ENV.setLoaded("borkdude.dynaload.js");
import "./cljs-runtime/malli.sci.js";
SHADOW_ENV.setLoaded("malli.sci.js");
import "./cljs-runtime/malli.core.js";
SHADOW_ENV.setLoaded("malli.core.js");
import "./cljs-runtime/malli.util.js";
SHADOW_ENV.setLoaded("malli.util.js");
import "./cljs-runtime/malli.error.js";
SHADOW_ENV.setLoaded("malli.error.js");
import "./cljs-runtime/knoxx.backend.contracts.validator.js";
SHADOW_ENV.setLoaded("knoxx.backend.contracts.validator.js");
import "./cljs-runtime/shadow.esm.esm_import$node_fs.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$node_fs.js");
import "./cljs-runtime/shadow.esm.esm_import$node_fs$promises.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$node_fs$promises.js");
import "./cljs-runtime/shadow.esm.esm_import$node_path.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$node_path.js");
import "./cljs-runtime/knoxx.backend.contracts.loader.js";
SHADOW_ENV.setLoaded("knoxx.backend.contracts.loader.js");
import "./cljs-runtime/knoxx.backend.runtime.contract_loader.js";
SHADOW_ENV.setLoaded("knoxx.backend.runtime.contract_loader.js");
import "./cljs-runtime/knoxx.backend.runtime.models.js";
SHADOW_ENV.setLoaded("knoxx.backend.runtime.models.js");
import "./cljs-runtime/knoxx.backend.http.js";
SHADOW_ENV.setLoaded("knoxx.backend.http.js");
import "./cljs-runtime/knoxx.backend.text.js";
SHADOW_ENV.setLoaded("knoxx.backend.text.js");
import "./cljs-runtime/knoxx.backend.agents.content.js";
SHADOW_ENV.setLoaded("knoxx.backend.agents.content.js");
import "./cljs-runtime/shadow.esm.esm_import$node_crypto.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$node_crypto.js");
import "./cljs-runtime/shadow.esm.esm_import$nodemailer.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$nodemailer.js");
import "./cljs-runtime/shadow.esm.esm_import$redis.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$redis.js");
import "./cljs-runtime/knoxx.backend.auth.session.js";
SHADOW_ENV.setLoaded("knoxx.backend.auth.session.js");
import "./cljs-runtime/knoxx.backend.runtime.state.js";
SHADOW_ENV.setLoaded("knoxx.backend.runtime.state.js");
import "./cljs-runtime/knoxx.backend.authz.js";
SHADOW_ENV.setLoaded("knoxx.backend.authz.js");
import "./cljs-runtime/knoxx.backend.redis_client.js";
SHADOW_ENV.setLoaded("knoxx.backend.redis_client.js");
import "./cljs-runtime/knoxx.backend.agents.policy.js";
SHADOW_ENV.setLoaded("knoxx.backend.agents.policy.js");
import "./cljs-runtime/knoxx.backend.actor_mailbox.js";
SHADOW_ENV.setLoaded("knoxx.backend.actor_mailbox.js");
import "./cljs-runtime/knoxx.backend.agent_context.js";
SHADOW_ENV.setLoaded("knoxx.backend.agent_context.js");
import "./cljs-runtime/knoxx.backend.util.time.js";
SHADOW_ENV.setLoaded("knoxx.backend.util.time.js");
import "./cljs-runtime/knoxx.backend.stores.session_store_registry.js";
SHADOW_ENV.setLoaded("knoxx.backend.stores.session_store_registry.js");
import "./cljs-runtime/knoxx.backend.quality_labels.js";
SHADOW_ENV.setLoaded("knoxx.backend.quality_labels.js");
import "./cljs-runtime/knoxx.backend.runtime.actor_scope.js";
SHADOW_ENV.setLoaded("knoxx.backend.runtime.actor_scope.js");
import "./cljs-runtime/knoxx.backend.openplanner_memory.js";
SHADOW_ENV.setLoaded("knoxx.backend.openplanner_memory.js");
import "./cljs-runtime/knoxx.backend.document_state.js";
SHADOW_ENV.setLoaded("knoxx.backend.document_state.js");
import "./cljs-runtime/knoxx.backend.runtime.config.js";
SHADOW_ENV.setLoaded("knoxx.backend.runtime.config.js");
import "./cljs-runtime/knoxx.backend.tools.registry.js";
SHADOW_ENV.setLoaded("knoxx.backend.tools.registry.js");
import "./cljs-runtime/knoxx.backend.contracts.roles.js";
SHADOW_ENV.setLoaded("knoxx.backend.contracts.roles.js");
import "./cljs-runtime/knoxx.backend.contracts.resolve.js";
SHADOW_ENV.setLoaded("knoxx.backend.contracts.resolve.js");
import "./cljs-runtime/knoxx.backend.mcp_bridge.js";
SHADOW_ENV.setLoaded("knoxx.backend.mcp_bridge.js");
import "./cljs-runtime/knoxx.backend.tooling.js";
SHADOW_ENV.setLoaded("knoxx.backend.tooling.js");
import "./cljs-runtime/knoxx.backend.core_memory.js";
SHADOW_ENV.setLoaded("knoxx.backend.core_memory.js");
import "./cljs-runtime/knoxx.backend.runtime.defaults.js";
SHADOW_ENV.setLoaded("knoxx.backend.runtime.defaults.js");
import "./cljs-runtime/malli.json_schema.js";
SHADOW_ENV.setLoaded("malli.json_schema.js");
import "./cljs-runtime/knoxx.backend.tools.shared.js";
SHADOW_ENV.setLoaded("knoxx.backend.tools.shared.js");
import "./cljs-runtime/knoxx.backend.tools.actor_credentials.js";
SHADOW_ENV.setLoaded("knoxx.backend.tools.actor_credentials.js");
import "./cljs-runtime/shadow.esm.esm_import$node_child_process.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$node_child_process.js");
import "./cljs-runtime/shadow.esm.esm_import$node_os.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$node_os.js");
import "./cljs-runtime/shadow.esm.esm_import$node_util.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$node_util.js");
import "./cljs-runtime/knoxx.backend.tools.media.js";
SHADOW_ENV.setLoaded("knoxx.backend.tools.media.js");
import "./cljs-runtime/knoxx.backend.tools.semantic.js";
SHADOW_ENV.setLoaded("knoxx.backend.tools.semantic.js");
import "./cljs-runtime/shadow.esm.esm_import$discord.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$discord.js");
import "./cljs-runtime/shadow.esm.esm_import$$discordjs$voice.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$$discordjs$voice.js");
import "./cljs-runtime/shadow.esm.esm_import$prism_media.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$prism_media.js");
import "./cljs-runtime/shadow.esm.esm_import$libsodium_wrappers.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$libsodium_wrappers.js");
import "./cljs-runtime/shadow.esm.esm_import$node_stream.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$node_stream.js");
import "./cljs-runtime/knoxx.backend.discord_gateway.js";
SHADOW_ENV.setLoaded("knoxx.backend.discord_gateway.js");
import "./cljs-runtime/shadow.esm.esm_import$$resvg$resvg_js.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$$resvg$resvg_js.js");
import "./cljs-runtime/knoxx.backend.tools.discord.js";
SHADOW_ENV.setLoaded("knoxx.backend.tools.discord.js");
import "./cljs-runtime/knoxx.backend.session_store.js";
SHADOW_ENV.setLoaded("knoxx.backend.session_store.js");
import "./cljs-runtime/knoxx.backend.tools.discord_voice.js";
SHADOW_ENV.setLoaded("knoxx.backend.tools.discord_voice.js");
import "./cljs-runtime/knoxx.backend.agent_templates.js";
SHADOW_ENV.setLoaded("knoxx.backend.agent_templates.js");
import "./cljs-runtime/knoxx.backend.tools.event_agents.js";
SHADOW_ENV.setLoaded("knoxx.backend.tools.event_agents.js");
import "./cljs-runtime/knoxx.backend.tools.events.js";
SHADOW_ENV.setLoaded("knoxx.backend.tools.events.js");
import "./cljs-runtime/knoxx.backend.tools.actors.js";
SHADOW_ENV.setLoaded("knoxx.backend.tools.actors.js");
import "./cljs-runtime/knoxx.backend.tools.openplanner.js";
SHADOW_ENV.setLoaded("knoxx.backend.tools.openplanner.js");
import "./cljs-runtime/knoxx.backend.tools.music.js";
SHADOW_ENV.setLoaded("knoxx.backend.tools.music.js");
import "./cljs-runtime/promesa.protocols.js";
SHADOW_ENV.setLoaded("promesa.protocols.js");
import "./cljs-runtime/promesa.util.js";
SHADOW_ENV.setLoaded("promesa.util.js");
import "./cljs-runtime/promesa.impl.promise.js";
SHADOW_ENV.setLoaded("promesa.impl.promise.js");
import "./cljs-runtime/promesa.exec.js";
SHADOW_ENV.setLoaded("promesa.exec.js");
import "./cljs-runtime/promesa.impl.js";
SHADOW_ENV.setLoaded("promesa.impl.js");
import "./cljs-runtime/promesa.core.js";
SHADOW_ENV.setLoaded("promesa.core.js");
import "./cljs-runtime/knoxx.backend.tools.openutau.js";
SHADOW_ENV.setLoaded("knoxx.backend.tools.openutau.js");
import "./cljs-runtime/knoxx.backend.tools.voice.js";
SHADOW_ENV.setLoaded("knoxx.backend.tools.voice.js");
import "./cljs-runtime/knoxx.backend.tools.bluesky.js";
SHADOW_ENV.setLoaded("knoxx.backend.tools.bluesky.js");
import "./cljs-runtime/knoxx.backend.tools.multimodal.js";
SHADOW_ENV.setLoaded("knoxx.backend.tools.multimodal.js");
import "./cljs-runtime/knoxx.backend.tools.workspace_media.js";
SHADOW_ENV.setLoaded("knoxx.backend.tools.workspace_media.js");
import "./cljs-runtime/knoxx.backend.tools.mcp.js";
SHADOW_ENV.setLoaded("knoxx.backend.tools.mcp.js");
import "./cljs-runtime/knoxx.backend.tools.contracts.js";
SHADOW_ENV.setLoaded("knoxx.backend.tools.contracts.js");
import "./cljs-runtime/shadow.esm.esm_import$node_net.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$node_net.js");
import "./cljs-runtime/knoxx.backend.tools.nrepl.js";
SHADOW_ENV.setLoaded("knoxx.backend.tools.nrepl.js");
import "./cljs-runtime/knoxx.backend.tools.session_mycology.js";
SHADOW_ENV.setLoaded("knoxx.backend.tools.session_mycology.js");
import "./cljs-runtime/knoxx.backend.agent_hydration.js";
SHADOW_ENV.setLoaded("knoxx.backend.agent_hydration.js");
import "./cljs-runtime/knoxx.backend.realtime.js";
SHADOW_ENV.setLoaded("knoxx.backend.realtime.js");
import "./cljs-runtime/knoxx.backend.run_state.js";
SHADOW_ENV.setLoaded("knoxx.backend.run_state.js");
import "./cljs-runtime/knoxx.backend.extension_runtime.js";
SHADOW_ENV.setLoaded("knoxx.backend.extension_runtime.js");
import "./cljs-runtime/shadow.esm.esm_import$$open_hax$eta_mu.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$$open_hax$eta_mu.js");
import "./cljs-runtime/knoxx.backend.agent_runtime.js";
SHADOW_ENV.setLoaded("knoxx.backend.agent_runtime.js");
import "./cljs-runtime/knoxx.backend.agents.tools.js";
SHADOW_ENV.setLoaded("knoxx.backend.agents.tools.js");
import "./cljs-runtime/knoxx.backend.turn_control.js";
SHADOW_ENV.setLoaded("knoxx.backend.turn_control.js");
import "./cljs-runtime/knoxx.backend.agents.stream.js";
SHADOW_ENV.setLoaded("knoxx.backend.agents.stream.js");
import "./cljs-runtime/knoxx.backend.agents.transcript.js";
SHADOW_ENV.setLoaded("knoxx.backend.agents.transcript.js");
import "./cljs-runtime/knoxx.backend.session_titles.js";
SHADOW_ENV.setLoaded("knoxx.backend.session_titles.js");
import "./cljs-runtime/knoxx.backend.agents.turn.js";
SHADOW_ENV.setLoaded("knoxx.backend.agents.turn.js");
import "./cljs-runtime/knoxx.backend.agents.recovery.js";
SHADOW_ENV.setLoaded("knoxx.backend.agents.recovery.js");
import "./cljs-runtime/knoxx.backend.agent_turns.js";
SHADOW_ENV.setLoaded("knoxx.backend.agent_turns.js");
import "./cljs-runtime/knoxx.backend.agent_resume.js";
SHADOW_ENV.setLoaded("knoxx.backend.agent_resume.js");
import "./cljs-runtime/knoxx.backend.routes.users.admin.js";
SHADOW_ENV.setLoaded("knoxx.backend.routes.users.admin.js");
import "./cljs-runtime/knoxx.backend.routes.admin.js";
SHADOW_ENV.setLoaded("knoxx.backend.routes.admin.js");
import "./cljs-runtime/shadow.cljs.modern.js";
SHADOW_ENV.setLoaded("shadow.cljs.modern.js");
import "./cljs-runtime/knoxx.backend.events.sources.discord.js";
SHADOW_ENV.setLoaded("knoxx.backend.events.sources.discord.js");
import "./cljs-runtime/knoxx.backend.agents.runner.js";
SHADOW_ENV.setLoaded("knoxx.backend.agents.runner.js");
import "./cljs-runtime/knoxx.backend.events.cron.js";
SHADOW_ENV.setLoaded("knoxx.backend.events.cron.js");
import "./cljs-runtime/knoxx.backend.runtime.roles.js";
SHADOW_ENV.setLoaded("knoxx.backend.runtime.roles.js");
import "./cljs-runtime/knoxx.backend.util.parse.js";
SHADOW_ENV.setLoaded("knoxx.backend.util.parse.js");
import "./cljs-runtime/knoxx.backend.triggers.control_config.js";
SHADOW_ENV.setLoaded("knoxx.backend.triggers.control_config.js");
import "./cljs-runtime/knoxx.backend.actions.loader.js";
SHADOW_ENV.setLoaded("knoxx.backend.actions.loader.js");
import "./cljs-runtime/knoxx.backend.actions.contract.js";
SHADOW_ENV.setLoaded("knoxx.backend.actions.contract.js");
import "./cljs-runtime/knoxx.backend.actions.registry.js";
SHADOW_ENV.setLoaded("knoxx.backend.actions.registry.js");
import "./cljs-runtime/knoxx.backend.actions.invoke_agent.js";
SHADOW_ENV.setLoaded("knoxx.backend.actions.invoke_agent.js");
import "./cljs-runtime/knoxx.backend.actions.invoke_sub_agent.js";
SHADOW_ENV.setLoaded("knoxx.backend.actions.invoke_sub_agent.js");
import "./cljs-runtime/knoxx.backend.actions.dispatch.js";
SHADOW_ENV.setLoaded("knoxx.backend.actions.dispatch.js");
import "./cljs-runtime/knoxx.backend.event_agents.js";
SHADOW_ENV.setLoaded("knoxx.backend.event_agents.js");
import "./cljs-runtime/knoxx.backend.events.dispatch.js";
SHADOW_ENV.setLoaded("knoxx.backend.events.dispatch.js");
import "./cljs-runtime/knoxx.backend.macros.js";
SHADOW_ENV.setLoaded("knoxx.backend.macros.js");
import "./cljs-runtime/knoxx.backend.routes.actors.js";
SHADOW_ENV.setLoaded("knoxx.backend.routes.actors.js");
import "./cljs-runtime/knoxx.backend.app_shapes.js";
SHADOW_ENV.setLoaded("knoxx.backend.app_shapes.js");
import "./cljs-runtime/knoxx.backend.events.runtime.js";
SHADOW_ENV.setLoaded("knoxx.backend.events.runtime.js");
import "./cljs-runtime/knoxx.backend.runtime.contract_validator.js";
SHADOW_ENV.setLoaded("knoxx.backend.runtime.contract_validator.js");
import "./cljs-runtime/knoxx.backend.routes.contracts.js";
SHADOW_ENV.setLoaded("knoxx.backend.routes.contracts.js");
import "./cljs-runtime/knoxx.backend.routes.documents.js";
SHADOW_ENV.setLoaded("knoxx.backend.routes.documents.js");
import "./cljs-runtime/knoxx.backend.guards.js";
SHADOW_ENV.setLoaded("knoxx.backend.guards.js");
import "./cljs-runtime/knoxx.backend.routes.memory.js";
SHADOW_ENV.setLoaded("knoxx.backend.routes.memory.js");
import "./cljs-runtime/knoxx.backend.routes.models.js";
SHADOW_ENV.setLoaded("knoxx.backend.routes.models.js");
import "./cljs-runtime/knoxx.backend.routes.tools.js";
SHADOW_ENV.setLoaded("knoxx.backend.routes.tools.js");
import "./cljs-runtime/knoxx.backend.routes.voice.js";
SHADOW_ENV.setLoaded("knoxx.backend.routes.voice.js");
import "./cljs-runtime/knoxx.backend.routes.workspace_media.js";
SHADOW_ENV.setLoaded("knoxx.backend.routes.workspace_media.js");
import "./cljs-runtime/knoxx.backend.audio_labels.js";
SHADOW_ENV.setLoaded("knoxx.backend.audio_labels.js");
import "./cljs-runtime/knoxx.backend.routes.studio.discord_scan.js";
SHADOW_ENV.setLoaded("knoxx.backend.routes.studio.discord_scan.js");
import "./cljs-runtime/knoxx.backend.routes.studio.js";
SHADOW_ENV.setLoaded("knoxx.backend.routes.studio.js");
import "./cljs-runtime/knoxx.backend.routes.translation.js";
SHADOW_ENV.setLoaded("knoxx.backend.routes.translation.js");
import "./cljs-runtime/knoxx.backend.routes.app.js";
SHADOW_ENV.setLoaded("knoxx.backend.routes.app.js");
import "./cljs-runtime/shadow.esm.esm_import$fastify.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$fastify.js");
import "./cljs-runtime/shadow.esm.esm_import$$fastify$cors.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$$fastify$cors.js");
import "./cljs-runtime/shadow.esm.esm_import$$fastify$websocket.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$$fastify$websocket.js");
import "./cljs-runtime/shadow.esm.esm_import$$fastify$multipart.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$$fastify$multipart.js");
import "./cljs-runtime/knoxx.backend.core.js";
SHADOW_ENV.setLoaded("knoxx.backend.core.js");
import "./cljs-runtime/knoxx.backend.discord_reaction_labels.js";
SHADOW_ENV.setLoaded("knoxx.backend.discord_reaction_labels.js");
import "./cljs-runtime/knoxx.backend.graceful_shutdown.js";
SHADOW_ENV.setLoaded("knoxx.backend.graceful_shutdown.js");
import "./cljs-runtime/shadow.esm.esm_import$$fastify$cookie.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$$fastify$cookie.js");
import "./cljs-runtime/shadow.esm.esm_import$$fastify$formbody.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$$fastify$formbody.js");
import "./cljs-runtime/knoxx.backend.http_server.js";
SHADOW_ENV.setLoaded("knoxx.backend.http_server.js");
import "./cljs-runtime/knoxx.backend.lifecycle.js";
SHADOW_ENV.setLoaded("knoxx.backend.lifecycle.js");
import "./cljs-runtime/honey.sql.protocols.js";
SHADOW_ENV.setLoaded("honey.sql.protocols.js");
import "./cljs-runtime/honey.sql.util.js";
SHADOW_ENV.setLoaded("honey.sql.util.js");
import "./cljs-runtime/honey.sql.js";
SHADOW_ENV.setLoaded("honey.sql.js");
import "./cljs-runtime/open_hax.contracts.schema.js";
SHADOW_ENV.setLoaded("open_hax.contracts.schema.js");
import "./cljs-runtime/knoxx.backend.policy.protocol.js";
SHADOW_ENV.setLoaded("knoxx.backend.policy.protocol.js");
import "./cljs-runtime/knoxx.backend.policy.edn_adapter.js";
SHADOW_ENV.setLoaded("knoxx.backend.policy.edn_adapter.js");
import "./cljs-runtime/knoxx.backend.policy.sql_adapter.js";
SHADOW_ENV.setLoaded("knoxx.backend.policy.sql_adapter.js");
import "./cljs-runtime/knoxx.backend.policy_db.actors.js";
SHADOW_ENV.setLoaded("knoxx.backend.policy_db.actors.js");
import "./cljs-runtime/shadow.esm.esm_import$pg.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$pg.js");
import "./cljs-runtime/knoxx.backend.policy_db.js";
SHADOW_ENV.setLoaded("knoxx.backend.policy_db.js");
import "./cljs-runtime/knoxx.backend.routes.auth.js";
SHADOW_ENV.setLoaded("knoxx.backend.routes.auth.js");
import "./cljs-runtime/knoxx.backend.mcp_expose.js";
SHADOW_ENV.setLoaded("knoxx.backend.mcp_expose.js");
import "./cljs-runtime/shadow.esm.esm_import$$modelcontextprotocol$sdk$server$mcp.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$$modelcontextprotocol$sdk$server$mcp.js");
import "./cljs-runtime/shadow.esm.esm_import$$modelcontextprotocol$sdk$server$streamableHttp.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$$modelcontextprotocol$sdk$server$streamableHttp.js");
import "./cljs-runtime/shadow.esm.esm_import$zod.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$zod.js");
import "./cljs-runtime/knoxx.backend.routes.mcp.js";
SHADOW_ENV.setLoaded("knoxx.backend.routes.mcp.js");
import "./cljs-runtime/knoxx.backend.eta_mu_session_ingester.js";
SHADOW_ENV.setLoaded("knoxx.backend.eta_mu_session_ingester.js");
import "./cljs-runtime/knoxx.backend.routes.tools.proxy.js";
SHADOW_ENV.setLoaded("knoxx.backend.routes.tools.proxy.js");
import "./cljs-runtime/knoxx.backend.bootstrap.js";
SHADOW_ENV.setLoaded("knoxx.backend.bootstrap.js");
import "./cljs-runtime/knoxx.backend.entrypoint.js";
SHADOW_ENV.setLoaded("knoxx.backend.entrypoint.js");
import "./cljs-runtime/shadow.module.server.append.js";
SHADOW_ENV.setLoaded("shadow.module.server.append.js");


try { knoxx.backend.entrypoint.init(); } catch (e) { console.error("An error occurred when calling (knoxx.backend.entrypoint/init)"); console.error(e); }
