name: Auto Merge

on:
  pull_request:
    types: [opened, ready_for_review]
  check_suite:
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: ${{ github.event.pull_request.draft == false && github.event.pull_request.head.repo.full_name == github.repository }}
    uses: open-hax/eta-mu/.github/workflows/auto-merge.yml@0823119585244bc5dfeea3c2b4cd64b0b0aa7cef # eta-mu main, 2026-08-02
    with:
      pr: ${{ github.event.pull_request.number }}
      merge-method: SQUASH
    secrets: inherit
